name: winbrother_hr_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.3+51

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_calendar_carousel: ^1.5.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_spinkit: "^4.1.2"
  flutter_native_image: ^0.0.5
  flutter_html: ^1.1.1
  flutter_downloader: ^1.5.2
  permission_handler: ^5.0.1+1
  path_provider:
  flutter_chips_input: ^1.9.4
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+17
  rxdart: ^0.25.0
  localstorage:
  easy_localization: ^1.0.3+1
  shared_preferences: ^0.5.3+5
#  shared_preferences: ^0.5.12+2
  flutter_i18n:
  http: ^0.12.0+1
  connectivity: 0.4.9+2
  ff_navigation_bar: ^0.1.5
  zawgyi_converter: ^0.0.4+pre-v0.2
  font_awesome_flutter: ^8.8.1
  circular_profile_avatar: ^1.0.6
  feather_icons_flutter: ^4.7.4
  flutter_mdetect: ^0.0.3
  rabbit_converter: ^0.0.1
  flutter_rounded_date_picker: ^1.0.4
  fdottedline: ^1.0.1
  bubble: ^1.1.9+1
  buttons_tabbar: ^1.0.0+1
  flutter_awesome_buttons: ^0.1.0
  get: ^3.12.1
  get_storage: ^1.0.0
  getwidget: ^1.1.0
  flutter_holo_date_picker: ^0.2.1
  auto_data: ^0.0.3
  dio: ^3.0.10
  logger:
  loading: ^1.0.2
  url_launcher: ^5.7.0
  flutter_sheet_localization:
  datetime_picker_formfield: ^1.0.0
  graphite: ^0.2.2
  table_calendar: ^2.3.1
  # onesignal_flutter: ^2.6.2
  # flutter_local_notifications: ^4.0.1
  google_fonts: ^1.1.1
  open_file: ^3.0.3
  photo_view: ^0.10.3
  date_format: ^1.0.9
  flutter_icons: ^1.1.0
  timeago: ^2.0.29
  syncfusion_flutter_calendar: ^18.4.43
  pull_to_refresh: 2.0.0
  modal_bottom_sheet: ^1.0.0
  flutter_rating_bar: ^3.2.0+1
  advance_pdf_viewer: 1.2.2
  flutter_full_pdf_viewer: ^1.0.6
  flutter_number_picker: ^0.0.8
  mime: ^0.9.7
  intl:
  auto_size_text: ^2.1.0
  data_table_2: ^2.1.1
  location: ^3.0.1
  geolocator: ^5.3.0
  android_intent: ^0.3.6+12
  image_size_getter: ^1.0.0
  flutter_typeahead:
  onesignal_flutter: ^3.3.0
  syncfusion_flutter_pdf: ^18.4.47-beta
  ext_storage: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.3.1
  auto_data_generator:
  flutter_sheet_localization_generator:
  numberpicker:
  multi_image_picker2: ^5.0.2
  thumbnailer:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.jpg
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
